import json
import os

notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Train Tiny Chemical LLM (Interactive Mode)\n",
    "\n",
    "This notebook trains a tiny character-level GPT to answer questions about chemicals.\n",
    "It learns to map **CAS Numbers** and **Functional Groups** to **SMILES** strings.\n",
    "\n",
    "**Format:** `User: CAS <cas>?\\nAssistant: SMILES <smiles><|end|>`\n",
    "**Device:** CPU (for stability)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import torch.nn as nn\n",
    "from torch.nn import functional as F\n",
    "import json\n",
    "import numpy as np\n",
    "\n",
    "# Force CPU for stability on Ryzen APU\n",
    "device = 'cpu'\n",
    "print(f\"Using device: {device}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Prepare Training Data (Chat Format)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "data_path = \"../data/for_train/universal_training_dataset_IR.jsonl\"\n",
    "text_data = []\n",
    "\n",
    "try:\n",
    "    with open(data_path, 'r') as f:\n",
    "        for line in f:\n",
    "            if line.strip():\n",
    "                record = json.loads(line)\n",
    "                smiles = record.get('smiles', '')\n",
    "                cas = record.get('cas_number', '')\n",
    "                labels = record.get('labels', [])\n",
    "                \n",
    "                if smiles:\n",
    "                    # 1. CAS -> SMILES\n",
    "                    if cas:\n",
    "                        text_data.append(f\"User: CAS {cas}?\\nAssistant: SMILES {smiles}<|end|>\")\n",
    "                    \n",
    "                    # 2. Group -> SMILES\n",
    "                    for label in labels:\n",
    "                        text_data.append(f\"User: Group {label}?\\nAssistant: SMILES {smiles}<|end|>\")\n",
    "\n",
    "except FileNotFoundError:\n",
    "    print(\"Data file not found. Using dummy chat data.\")\n",
    "    # Dummy data for demonstration\n",
    "    dummy_pairs = [\n",
    "        (\"CAS 100-42-5\", \"C=CC1=CC=CC=C1\"),\n",
    "        (\"Group Aromatic\", \"C=CC1=CC=CC=C1\"),\n",
    "        (\"Group Alkene\", \"C=CC1=CC=CC=C1\"),\n",
    "        (\"CAS 64-17-5\", \"CCO\"),\n",
    "        (\"Group Alcohol\", \"CCO\"),\n",
    "        (\"CAS 71-43-2\", \"c1ccccc1\"),\n",
    "        (\"Group Aromatic\", \"c1ccccc1\")\n",
    "    ] * 50\n",
    "    for q, a in dummy_pairs:\n",
    "        text_data.append(f\"User: {q}?\\nAssistant: SMILES {a}<|end|>\")\n",
    "\n",
    "text = \"\\n\".join(text_data)\n",
    "print(f\"Total training samples: {len(text_data)}\")\n",
    "print(f\"Total characters: {len(text)}\")\n",
    "print(\"Sample data:\")\n",
    "print(text[:200])\n",
    "\n",
    "# Tokenizer\n",
    "chars = sorted(list(set(text)))\n",
    "vocab_size = len(chars)\n",
    "stoi = { ch:i for i,ch in enumerate(chars) }\n",
    "itos = { i:ch for i,ch in enumerate(chars) }\n",
    "encode = lambda s: [stoi[c] for c in s]\n",
    "decode = lambda l: ''.join([itos[i] for i in l])\n",
    "\n",
    "data = torch.tensor(encode(text), dtype=torch.long)\n",
    "n = int(0.9*len(data))\n",
    "train_data = data[:n]\n",
    "val_data = data[n:]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Model Definition"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Hyperparameters\n",
    "batch_size = 32\n",
    "block_size = 128 # Increased for chat context\n",
    "if len(train_data) < block_size:\n",
    "    block_size = len(train_data) - 1\n",
    "\n",
    "max_iters = 2000\n",
    "eval_interval = 200\n",
    "learning_rate = 1e-3\n",
    "n_embd = 128\n",
    "n_head = 4\n",
    "n_layer = 4\n",
    "dropout = 0.1\n",
    "\n",
    "class Head(nn.Module):\n",
    "    def __init__(self, head_size):\n",
    "        super().__init__()\n",
    "        self.key = nn.Linear(n_embd, head_size, bias=False)\n",
    "        self.query = nn.Linear(n_embd, head_size, bias=False)\n",
    "        self.value = nn.Linear(n_embd, head_size, bias=False)\n",
    "        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))\n",
    "        self.dropout = nn.Dropout(dropout)\n",
    "\n",
    "    def forward(self, x):\n",
    "        B,T,C = x.shape\n",
    "        k = self.key(x)\n",
    "        q = self.query(x)\n",
    "        wei = q @ k.transpose(-2, -1) * C**-0.5\n",
    "        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))\n",
    "        wei = F.softmax(wei, dim=-1)\n",
    "        wei = self.dropout(wei)\n",
    "        v = self.value(x)\n",
    "        out = wei @ v\n",
    "        return out\n",
    "\n",
    "class MultiHeadAttention(nn.Module):\n",
    "    def __init__(self, num_heads, head_size):\n",
    "        super().__init__()\n",
    "        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])\n",
    "        self.proj = nn.Linear(n_embd, n_embd)\n",
    "        self.dropout = nn.Dropout(dropout)\n",
    "\n",
    "    def forward(self, x):\n",
    "        out = torch.cat([h(x) for h in self.heads], dim=-1)\n",
    "        out = self.proj(out)\n",
    "        return self.dropout(out)\n",
    "\n",
    "class FeedFoward(nn.Module):\n",
    "    def __init__(self, n_embd):\n",
    "        super().__init__()\n",
    "        self.net = nn.Sequential(\n",
    "            nn.Linear(n_embd, 4 * n_embd),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(4 * n_embd, n_embd),\n",
    "            nn.Dropout(dropout),\n",
    "        )\n",
    "\n",
    "    def forward(self, x):\n",
    "        return self.net(x)\n",
    "\n",
    "class Block(nn.Module):\n",
    "    def __init__(self, n_embd, n_head):\n",
    "        super().__init__()\n",
    "        head_size = n_embd // n_head\n",
    "        self.sa = MultiHeadAttention(n_head, head_size)\n",
    "        self.ffwd = FeedFoward(n_embd)\n",
    "        self.ln1 = nn.LayerNorm(n_embd)\n",
    "        self.ln2 = nn.LayerNorm(n_embd)\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = x + self.sa(self.ln1(x))\n",
    "        x = x + self.ffwd(self.ln2(x))\n",
    "        return x\n",
    "\n",
    "class TinyGPT(nn.Module):\n",
    "    def __init__(self):\n",
    "        super().__init__()\n",
    "        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)\n",
    "        self.position_embedding_table = nn.Embedding(block_size, n_embd)\n",
    "        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])\n",
    "        self.ln_f = nn.LayerNorm(n_embd)\n",
    "        self.lm_head = nn.Linear(n_embd, vocab_size)\n",
    "\n",
    "    def forward(self, idx, targets=None):\n",
    "        B, T = idx.shape\n",
    "        tok_emb = self.token_embedding_table(idx)\n",
    "        pos_emb = self.position_embedding_table(torch.arange(T, device=device))\n",
    "        x = tok_emb + pos_emb\n",
    "        x = self.blocks(x)\n",
    "        x = self.ln_f(x)\n",
    "        logits = self.lm_head(x)\n",
    "\n",
    "        if targets is None:\n",
    "            loss = None\n",
    "        else:\n",
    "            B, T, C = logits.shape\n",
    "            logits = logits.view(B*T, C)\n",
    "            targets = targets.view(B*T)\n",
    "            loss = F.cross_entropy(logits, targets)\n",
    "\n",
    "        return logits, loss\n",
    "\n",
    "    def generate(self, idx, max_new_tokens):\n",
    "        for _ in range(max_new_tokens):\n",
    "            idx_cond = idx[:, -block_size:]\n",
    "            logits, loss = self(idx_cond)\n",
    "            logits = logits[:, -1, :]\n",
    "            probs = F.softmax(logits, dim=-1)\n",
    "            idx_next = torch.multinomial(probs, num_samples=1)\n",
    "            idx = torch.cat((idx, idx_next), dim=1)\n",
    "            # Stop if <|end|> token is generated (if we had one, but here we just stop at newline or max tokens)\n",
    "            if decode([idx_next.item()]) == '<': # Simple heuristic for <|end|>\n",
    "                 break\n",
    "        return idx\n",
    "\n",
    "model = TinyGPT()\n",
    "m = model.to(device)\n",
    "print(f\"Model parameters: {sum(p.numel() for p in m.parameters())/1e3} K\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Train"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_batch(split):\n",
    "    data_src = train_data if split == 'train' else val_data\n",
    "    ix = torch.randint(len(data_src) - block_size, (batch_size,))\n",
    "    x = torch.stack([data_src[i:i+block_size] for i in ix])\n",
    "    y = torch.stack([data_src[i+1:i+block_size+1] for i in ix])\n",
    "    x, y = x.to(device), y.to(device)\n",
    "    return x, y\n",
    "\n",
    "optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)\n",
    "\n",
    "print(\"Starting training...\")\n",
    "for iter in range(max_iters):\n",
    "    xb, yb = get_batch('train')\n",
    "    logits, loss = model(xb, yb)\n",
    "    optimizer.zero_grad(set_to_none=True)\n",
    "    loss.backward()\n",
    "    optimizer.step()\n",
    "\n",
    "    if iter % eval_interval == 0:\n",
    "        print(f\"step {iter}: loss {loss.item():.4f}\")\n",
    "\n",
    "print(f\"Final loss: {loss.item():.4f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Interactive Chat"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def chat(query):\n",
    "    prompt = f\"User: {query}?\\nAssistant:\"\n",
    "    context = torch.tensor(encode(prompt), dtype=torch.long, device=device).unsqueeze(0)\n",
    "    response_idx = m.generate(context, max_new_tokens=100)\n",
    "    response_text = decode(response_idx[0].tolist())\n",
    "    # Extract only the assistant's part\n",
    "    if \"Assistant:\" in response_text:\n",
    "        return response_text.split(\"Assistant:\")[1].split(\"<|end|>\")[0].strip()\n",
    "    return response_text\n",
    "\n",
    "print(\"🤖 Tiny Chemical LLM Ready! Type 'exit' to stop.\")\n",
    "print(\"Try asking: 'CAS 100-42-5' or 'Group Alcohol'\")\n",
    "\n",
    "while True:\n",
    "    user_input = input(\"You: \")\n",
    "    if user_input.lower() in ['exit', 'quit']:\n",
    "        break\n",
    "    \n",
    "    response = chat(user_input)\n",
    "    print(f\"Bot: {response}\\n\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open("notebook_jupyter/train_tiny_chemical_llm.ipynb", "w") as f:
    json.dump(notebook_content, f, indent=1)

print("Notebook created successfully!")
